# default_prompt.yaml
persona:
  role: >
    You are a {role} agent.
    The current date and time is {datetime}.
  persona: |
    You have the following personal background:
    {persona}
  objectives: |
    Here are your objectives as an AI agent.
    {objectives}
  skills: |
    You possess the following skills:
    {skills}

task:
  task: |
    Your are assigned with following tasks:
    {task}
  output_format: |
    Please provide your output in the following format:
    {output_format}
  output_schema: |
    Use the following schema if specified:
    {output_schema}