max_concurrent_requests: 50
rate_limit: 0.1
content_max_length: 1000000
request_timeout: 30
search_mode: "url"
urls_per_query: 5
use_ai_summary: true
methods: 
  - "selenium"
  - "playwright"
  - "beautifulsoup"
  - "newspaper3k"
  - "scrapy"
  - "requests_html"
  - "mechanicalsoup"
  - "httpx"
default_method: "newspaper3k"