query: "latest tech stock market trends"
max_concurrent_requests: 50
rate_limit: 0.1
content_max_length: 1000000
request_timeout: 30
urls_per_query: 5
use_ai_summary: true
methods: 
  - "selenium"
  - "playwright"
  - "beautifulsoup"
  - "newspaper3k"
  - "scrapy"
  - "requests_html"
  - "mechanicalsoup"
  - "httpx"
default_method: "newspaper3k"
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
  Accept-Language: "en-US,en;q=0.5"

# Add this section if it's missing
llm_configs:
  search_query_generation:
    client: "openai"
    model: "gpt-4"
    max_tokens: 1000
    temperature: 0.7
    use_cache: true
    system_prompt: "You are an expert market research analyst specializing in technology stocks."
    prompt_template: "Generate 5 specific search queries related to: {query}"
  content_analysis:
    client: "openai"
    model: "gpt-4"
    max_tokens: 2000
    temperature: 0.5
    use_cache: true
    system_prompt: "You are an expert financial analyst."
    prompt_template: "{prompt}"